events {}

http {

    include /etc/nginx/mime.types;

    default_type application/octet-stream;

    resolver 127.0.0.11 valid=10s;


    server {

        listen 80;
        listen [::]:80;

        server_name localhost;


# ===============================
# CCTV FRONTEND
# ===============================

location ^~ /cctv/ {

    proxy_pass http://frontend-cctv/;

    proxy_http_version 1.1;

    proxy_set_header Host $host;

    proxy_set_header X-Real-IP $remote_addr;

    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_set_header X-Forwarded-Proto $scheme;
}


        # ===============================
        # API CCTV
        # ===============================
        location ^~ /api/ {

            set $backend_cctv backend-cctv;

            proxy_pass http://$backend_cctv:8081;

            proxy_http_version 1.1;

            proxy_set_header Host $host;

            proxy_set_header X-Real-IP $remote_addr;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header Authorization $http_authorization;
        }


        # ===============================
        # LOGIN HSE
        # ===============================
        location ^~ /login/hse/ {

            set $frontend_hse frontend-hse;

            proxy_pass http://$frontend_hse/;

            proxy_http_version 1.1;
        }


        # ===============================
        # LOGIN PARAMEDIS
        # ===============================
        location ^~ /login/paramedis/ {

            set $frontend_paramedis frontend-paramedis;

            proxy_pass http://$frontend_paramedis/;

            proxy_http_version 1.1;
        }


        # ===============================
        # COMPANY PROFILE
        # ===============================
        location / {

            set $company_profile company-profile;

            proxy_pass http://$company_profile;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
        }

    }
}